export const trendingPlayers = {
  topPlayers: [
    {
      event: {
        tournament: {
          name: "MLS",
          slug: "mls",
          category: {
            name: "USA",
            slug: "usa",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 26,
            flag: "usa",
            alpha2: "US",
          },
          uniqueTournament: {
            name: "MLS",
            slug: "mls",
            primaryColorHex: "#e2231a",
            secondaryColorHex: "#062f69",
            category: {
              name: "USA",
              slug: "usa",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 26,
              flag: "usa",
              alpha2: "US",
            },
            userCount: 100414,
            id: 242,
            displayInverseHomeAwayTeams: false,
          },
          priority: 345,
          isLive: false,
          id: 18,
        },
        customId: "gabsccKc",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Inter Miami CF",
          slug: "inter-miami-cf",
          shortName: "Inter Miami",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 712097,
          nameCode: "MIA",
          disabled: false,
          national: false,
          type: 0,
          id: 337602,
          teamColors: {
            primary: "#212322",
            secondary: "#f6b5cc",
            text: "#f6b5cc",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0625\u0646\u062a\u0631 \u0645\u064a\u0627\u0645\u064a",
              ru: "\u0418\u043d\u0442\u0435\u0440 \u041c\u0430\u0439\u0430\u043c\u0438",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "New York Red Bulls",
          slug: "new-york-red-bulls",
          shortName: "NY Red Bulls",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 17627,
          nameCode: "NY",
          disabled: false,
          national: false,
          type: 0,
          id: 2506,
          teamColors: {
            primary: "#ffffff",
            secondary: "#cc0000",
            text: "#cc0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0646\u064a\u0648\u064a\u0648\u0631\u0643 \u0631\u064a\u062f \u0628\u0648\u0644\u0632",
              ru: "\u041d\u044c\u044e \u0419\u043e\u0440\u043a \u0420\u0435\u0434 \u0411\u0443\u043b\u043b\u0441",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 6,
          display: 6,
          period1: 0,
          period2: 6,
          normaltime: 6,
        },
        awayScore: {
          current: 2,
          display: 2,
          period1: 1,
          period2: 1,
          normaltime: 2,
        },
        hasXg: true,
        id: 11911622,
        startTimestamp: 1714865400,
        slug: "inter-miami-cf-new-york-red-bulls",
        finalResultOnly: false,
      },
      totalPass: 46,
      accuratePass: 35,
      totalLongBalls: 4,
      accurateLongBalls: 3,
      goalAssist: 5,
      totalCross: 3,
      accurateCross: 1,
      duelLost: 5,
      duelWon: 6,
      dispossessed: 2,
      totalContest: 6,
      wonContest: 3,
      bigChanceCreated: 5,
      bigChanceMissed: 1,
      shotOffTarget: 1,
      onTargetScoringAttempt: 2,
      blockedScoringAttempt: 2,
      goals: 1,
      totalTackle: 1,
      wasFouled: 2,
      minutesPlayed: 90,
      touches: 70,
      rating: 10,
      possessionLostCtrl: 18,
      expectedGoals: 0.6369,
      team: {
        name: "Inter Miami CF",
        slug: "inter-miami-cf",
        shortName: "Inter Miami",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 712097,
        nameCode: "MIA",
        disabled: false,
        national: false,
        type: 0,
        id: 337602,
        teamColors: {
          primary: "#212322",
          secondary: "#f6b5cc",
          text: "#f6b5cc",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0625\u0646\u062a\u0631 \u0645\u064a\u0627\u0645\u064a",
            ru: "\u0418\u043d\u0442\u0435\u0440 \u041c\u0430\u0439\u0430\u043c\u0438",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Lionel Messi",
        slug: "lionel-messi",
        shortName: "L. Messi",
        position: "F",
        jerseyNumber: "10",
        userCount: 756955,
        id: 12994,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 551491200,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0645\u064a\u0633\u064a, \u0644\u064a\u0648\u0646\u064a\u0644",
          },
          shortNameTranslation: { ar: "\u0644. \u0645\u064a\u0633\u064a" },
        },
      },
      keyPass: 6,
      ratingVersions: { original: 10, alternative: 10 },
      expectedAssists: 0.912981,
    },
    {
      event: {
        tournament: {
          name: "MLS",
          slug: "mls",
          category: {
            name: "USA",
            slug: "usa",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 26,
            flag: "usa",
            alpha2: "US",
          },
          uniqueTournament: {
            name: "MLS",
            slug: "mls",
            primaryColorHex: "#e2231a",
            secondaryColorHex: "#062f69",
            category: {
              name: "USA",
              slug: "usa",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 26,
              flag: "usa",
              alpha2: "US",
            },
            userCount: 100414,
            id: 242,
            displayInverseHomeAwayTeams: false,
          },
          priority: 345,
          isLive: false,
          id: 18,
        },
        customId: "gabsccKc",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Inter Miami CF",
          slug: "inter-miami-cf",
          shortName: "Inter Miami",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 712097,
          nameCode: "MIA",
          disabled: false,
          national: false,
          type: 0,
          id: 337602,
          teamColors: {
            primary: "#212322",
            secondary: "#f6b5cc",
            text: "#f6b5cc",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0625\u0646\u062a\u0631 \u0645\u064a\u0627\u0645\u064a",
              ru: "\u0418\u043d\u0442\u0435\u0440 \u041c\u0430\u0439\u0430\u043c\u0438",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "New York Red Bulls",
          slug: "new-york-red-bulls",
          shortName: "NY Red Bulls",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 17627,
          nameCode: "NY",
          disabled: false,
          national: false,
          type: 0,
          id: 2506,
          teamColors: {
            primary: "#ffffff",
            secondary: "#cc0000",
            text: "#cc0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0646\u064a\u0648\u064a\u0648\u0631\u0643 \u0631\u064a\u062f \u0628\u0648\u0644\u0632",
              ru: "\u041d\u044c\u044e \u0419\u043e\u0440\u043a \u0420\u0435\u0434 \u0411\u0443\u043b\u043b\u0441",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 6,
          display: 6,
          period1: 0,
          period2: 6,
          normaltime: 6,
        },
        awayScore: {
          current: 2,
          display: 2,
          period1: 1,
          period2: 1,
          normaltime: 2,
        },
        hasXg: true,
        id: 11911622,
        startTimestamp: 1714865400,
        slug: "inter-miami-cf-new-york-red-bulls",
        finalResultOnly: false,
      },
      totalPass: 29,
      accuratePass: 21,
      totalLongBalls: 2,
      accurateLongBalls: 1,
      goalAssist: 1,
      aerialLost: 4,
      aerialWon: 2,
      duelLost: 7,
      duelWon: 5,
      challengeLost: 1,
      totalContest: 3,
      wonContest: 2,
      bigChanceCreated: 1,
      onTargetScoringAttempt: 3,
      goals: 3,
      totalClearance: 1,
      wasFouled: 1,
      fouls: 1,
      minutesPlayed: 84,
      touches: 42,
      rating: 10,
      possessionLostCtrl: 13,
      expectedGoals: 1.0914,
      team: {
        name: "Inter Miami CF",
        slug: "inter-miami-cf",
        shortName: "Inter Miami",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 712097,
        nameCode: "MIA",
        disabled: false,
        national: false,
        type: 0,
        id: 337602,
        teamColors: {
          primary: "#212322",
          secondary: "#f6b5cc",
          text: "#f6b5cc",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0625\u0646\u062a\u0631 \u0645\u064a\u0627\u0645\u064a",
            ru: "\u0418\u043d\u0442\u0435\u0440 \u041c\u0430\u0439\u0430\u043c\u0438",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Luis Su\u00e1rez",
        slug: "luis-suarez",
        shortName: "L. Su\u00e1rez",
        position: "F",
        jerseyNumber: "9",
        userCount: 103863,
        id: 16943,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 538444800,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0633\u0648\u0627\u0631\u064a\u0632, \u0644\u0648\u064a\u0633",
          },
          shortNameTranslation: {
            ar: "\u0644. \u0633\u0648\u0627\u0631\u064a\u0632",
          },
        },
      },
      keyPass: 3,
      ratingVersions: { original: 10, alternative: 9.9 },
      expectedAssists: 0.124074,
    },
    {
      event: {
        tournament: {
          name: "MLS",
          slug: "mls",
          category: {
            name: "USA",
            slug: "usa",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 26,
            flag: "usa",
            alpha2: "US",
          },
          uniqueTournament: {
            name: "MLS",
            slug: "mls",
            primaryColorHex: "#e2231a",
            secondaryColorHex: "#062f69",
            category: {
              name: "USA",
              slug: "usa",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 26,
              flag: "usa",
              alpha2: "US",
            },
            userCount: 100414,
            id: 242,
            displayInverseHomeAwayTeams: false,
          },
          priority: 345,
          isLive: false,
          id: 18,
        },
        customId: "gPismcKc",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Nashville SC",
          slug: "nashville-sc",
          shortName: "Nashville",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 18680,
          nameCode: "NSC",
          disabled: false,
          national: false,
          type: 0,
          id: 337612,
          teamColors: {
            primary: "#0f1545",
            secondary: "#ece83a",
            text: "#ece83a",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0646\u0627\u062f\u064a \u0646\u0627\u0634\u0641\u064a\u0644 \u0623\u0633 \u0633\u064a",
              ru: "\u041d\u044d\u0448\u0432\u0438\u043b\u043b",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "CF Montreal",
          slug: "cf-montreal",
          shortName: "Montr\u00e9al",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 11596,
          nameCode: "MON",
          disabled: false,
          national: false,
          type: 0,
          id: 22006,
          teamColors: {
            primary: "#0033ff",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0645\u0648\u0646\u062a\u0631\u064a\u0627\u0644",
              ru: "\u041c\u043e\u043d\u0440\u0435\u0430\u043b\u044c",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 4,
          display: 4,
          period1: 2,
          period2: 2,
          normaltime: 4,
        },
        awayScore: {
          current: 1,
          display: 1,
          period1: 0,
          period2: 1,
          normaltime: 1,
        },
        hasXg: true,
        id: 11911628,
        startTimestamp: 1714869000,
        slug: "nashville-sc-cf-montreal",
        finalResultOnly: false,
      },
      totalPass: 17,
      accuratePass: 10,
      totalLongBalls: 1,
      totalCross: 1,
      accurateCross: 1,
      aerialLost: 4,
      aerialWon: 3,
      duelLost: 10,
      duelWon: 9,
      dispossessed: 1,
      totalContest: 1,
      wonContest: 1,
      bigChanceCreated: 2,
      bigChanceMissed: 1,
      shotOffTarget: 2,
      onTargetScoringAttempt: 3,
      blockedScoringAttempt: 1,
      hitWoodwork: 1,
      goals: 3,
      totalTackle: 2,
      wasFouled: 3,
      fouls: 5,
      minutesPlayed: 90,
      touches: 36,
      rating: 10,
      possessionLostCtrl: 10,
      expectedGoals: 0.8085,
      team: {
        name: "Nashville SC",
        slug: "nashville-sc",
        shortName: "Nashville",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 18680,
        nameCode: "NSC",
        disabled: false,
        national: false,
        type: 0,
        id: 337612,
        teamColors: {
          primary: "#0f1545",
          secondary: "#ece83a",
          text: "#ece83a",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0646\u0627\u062f\u064a \u0646\u0627\u0634\u0641\u064a\u0644 \u0623\u0633 \u0633\u064a",
            ru: "\u041d\u044d\u0448\u0432\u0438\u043b\u043b",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Sam Surridge",
        firstName: "",
        lastName: "",
        slug: "sam-surridge",
        shortName: "S. Surridge",
        position: "F",
        jerseyNumber: "9",
        userCount: 318,
        id: 817567,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 901584000,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0633\u0648\u0631\u064a\u062c, \u0633\u0627\u0645",
          },
          shortNameTranslation: {
            ar: "\u0633. \u0633\u0648\u0631\u064a\u062c",
          },
        },
      },
      keyPass: 2,
      ratingVersions: { original: 10, alternative: 10 },
      expectedAssists: 0.364571,
    },
    {
      event: {
        tournament: {
          name: "The FA Women's Super League",
          slug: "the-fa-womens-super-league",
          category: {
            name: "England",
            slug: "england",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 1,
            flag: "england",
            alpha2: "EN",
          },
          uniqueTournament: {
            name: "The FA Women's Super League",
            slug: "the-fa-womens-super-league",
            primaryColorHex: "#1c0f32",
            secondaryColorHex: "#fc4342",
            category: {
              name: "England",
              slug: "england",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 1,
              flag: "england",
              alpha2: "EN",
            },
            userCount: 21868,
            id: 1044,
            displayInverseHomeAwayTeams: false,
          },
          priority: 20,
          isLive: false,
          id: 15635,
        },
        customId: "dkxstKB",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Chelsea FC Women",
          slug: "chelsea-fc-women",
          shortName: "Chelsea",
          gender: "F",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 95386,
          nameCode: "CFC",
          disabled: false,
          national: false,
          type: 0,
          id: 66768,
          teamColors: {
            primary: "#0310a7",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u0427\u0435\u043b\u0441\u0438 \u041b\u0424\u041a",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Bristol City WFC",
          slug: "bristol-city-wfc",
          shortName: "Bristol City",
          gender: "F",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 2465,
          nameCode: "BRC",
          national: false,
          type: 0,
          id: 55503,
          teamColors: {
            primary: "#ff0000",
            secondary: "#ff0000",
            text: "#ff0000",
          },
        },
        homeScore: {
          current: 8,
          display: 8,
          period1: 2,
          period2: 6,
          normaltime: 8,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        id: 11453519,
        startTimestamp: 1714931100,
        slug: "chelsea-fc-women-bristol-city-wfc",
        finalResultOnly: false,
      },
      totalPass: 45,
      accuratePass: 32,
      totalLongBalls: 1,
      goalAssist: 1,
      totalCross: 18,
      accurateCross: 5,
      duelLost: 1,
      duelWon: 2,
      challengeLost: 1,
      totalContest: 1,
      wonContest: 1,
      bigChanceCreated: 1,
      onTargetScoringAttempt: 4,
      goals: 4,
      totalTackle: 1,
      totalOffside: 1,
      minutesPlayed: 90,
      touches: 77,
      rating: 10,
      possessionLostCtrl: 29,
      team: {
        name: "Chelsea FC Women",
        slug: "chelsea-fc-women",
        shortName: "Chelsea",
        gender: "F",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 95386,
        nameCode: "CFC",
        disabled: false,
        national: false,
        type: 0,
        id: 66768,
        teamColors: {
          primary: "#0310a7",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ru: "\u0427\u0435\u043b\u0441\u0438 \u041b\u0424\u041a",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Guro Reiten",
        slug: "guro-reiten",
        shortName: "G. Reiten",
        position: "M",
        jerseyNumber: "11",
        userCount: 1414,
        id: 96004,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 775180800,
      },
      keyPass: 6,
      ratingVersions: { original: 10, alternative: 10 },
    },
    {
      event: {
        tournament: {
          name: "A-League Playoffs",
          slug: "a-league-playoffs",
          category: {
            name: "Australia",
            slug: "australia",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 34,
            flag: "australia",
            alpha2: "AU",
          },
          uniqueTournament: {
            name: "A-League Men",
            slug: "a-league-men",
            primaryColorHex: "#fe5001",
            secondaryColorHex: "#8e0a06",
            category: {
              name: "Australia",
              slug: "australia",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 34,
              flag: "australia",
              alpha2: "AU",
            },
            userCount: 26947,
            id: 136,
            displayInverseHomeAwayTeams: false,
          },
          priority: 264,
          isLive: false,
          id: 7514,
        },
        customId: "vucskUq",
        status: { code: 120, description: "AP", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Melbourne Victory",
          slug: "melbourne-victory",
          shortName: "Melbourne Victory",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 18431,
          nameCode: "MEL",
          disabled: false,
          national: false,
          type: 0,
          id: 5970,
          teamColors: {
            primary: "#003366",
            secondary: "#003366",
            text: "#003366",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0645\u0644\u0628\u0648\u0631\u0646 \u0641\u064a\u0643\u062a\u0648\u0631\u064a",
              ru: "\u041c\u0435\u043b\u044c\u0431\u0443\u0440\u043d \u0412\u0438\u043a\u0442\u043e\u0440\u0438 \u0424\u041a",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Melbourne City",
          slug: "melbourne-city",
          shortName: "Melbourne City",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 30941,
          nameCode: "MBC",
          disabled: false,
          national: false,
          type: 0,
          id: 42210,
          teamColors: {
            primary: "#ffffff",
            secondary: "#66ccff",
            text: "#66ccff",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u041c\u0435\u043b\u044c\u0431\u0443\u0440\u043d \u0421\u0438\u0442\u0438",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 4,
          display: 1,
          period1: 0,
          period2: 1,
          normaltime: 1,
          extra1: 0,
          extra2: 0,
          overtime: 0,
          penalties: 3,
        },
        awayScore: {
          current: 3,
          display: 1,
          period1: 1,
          period2: 0,
          normaltime: 1,
          extra1: 0,
          extra2: 0,
          overtime: 0,
          penalties: 2,
        },
        id: 12287958,
        startTimestamp: 1714892400,
        slug: "melbourne-city-melbourne-victory",
        finalResultOnly: false,
      },
      totalPass: 46,
      accuratePass: 33,
      totalLongBalls: 27,
      accurateLongBalls: 15,
      duelWon: 1,
      totalContest: 1,
      wonContest: 1,
      totalClearance: 1,
      goodHighClaim: 1,
      savedShotsFromInsideTheBox: 7,
      penaltySave: 1,
      saves: 9,
      punches: 1,
      minutesPlayed: 120,
      touches: 60,
      rating: 10,
      possessionLostCtrl: 13,
      penaltyShootoutSave: 3,
      penaltyShootoutGoal: 1,
      team: {
        name: "Melbourne Victory",
        slug: "melbourne-victory",
        shortName: "Melbourne Victory",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 18431,
        nameCode: "MEL",
        disabled: false,
        national: false,
        type: 0,
        id: 5970,
        teamColors: {
          primary: "#003366",
          secondary: "#003366",
          text: "#003366",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0645\u0644\u0628\u0648\u0631\u0646 \u0641\u064a\u0643\u062a\u0648\u0631\u064a",
            ru: "\u041c\u0435\u043b\u044c\u0431\u0443\u0440\u043d \u0412\u0438\u043a\u0442\u043e\u0440\u0438 \u0424\u041a",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Paul Izzo",
        slug: "paul-izzo",
        shortName: "P. Izzo",
        position: "G",
        jerseyNumber: "20",
        userCount: 29,
        id: 155925,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 789350400,
      },
      ratingVersions: { original: 10, alternative: 10 },
    },
    {
      event: {
        tournament: {
          name: "Chinese Super League",
          slug: "chinese-super-league",
          category: {
            name: "China",
            slug: "china",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 99,
            flag: "china",
            alpha2: "CN",
          },
          uniqueTournament: {
            name: "CFA Super League",
            slug: "cfa-super-league",
            primaryColorHex: "#f16327",
            secondaryColorHex: "#bc0416",
            category: {
              name: "China",
              slug: "china",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 99,
              flag: "china",
              alpha2: "CN",
            },
            userCount: 18723,
            id: 649,
            displayInverseHomeAwayTeams: false,
          },
          priority: 257,
          isLive: false,
          id: 652,
        },
        customId: "MFqsGBmc",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 2,
        homeTeam: {
          name: "Shenzhen City",
          slug: "shenzhen-city",
          shortName: "Shenzhen",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 5115,
          nameCode: "SCI",
          disabled: false,
          national: false,
          type: 0,
          id: 281331,
          teamColors: {
            primary: "#fde910",
            secondary: "#be2d1f",
            text: "#be2d1f",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0633\u064a\u062a\u0634\u0648\u0627\u0646 \u062c\u0648\u0646\u064a\u0648",
              ru: "\u0421\u044b\u0447\u0443\u0430\u043d\u044c \u0426\u0437\u044e\u043d\u044e",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Shanghai Port",
          slug: "shanghai-port",
          shortName: "Port",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 25453,
          nameCode: "SHP",
          disabled: false,
          national: false,
          type: 0,
          id: 41537,
          teamColors: {
            primary: "#d90000",
            secondary: "#840000",
            text: "#840000",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u0428\u0430\u043d\u0445\u0430\u0439 \u041f\u043e\u0440\u0442",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        awayScore: {
          current: 6,
          display: 6,
          period1: 3,
          period2: 3,
          normaltime: 6,
        },
        id: 12060301,
        startTimestamp: 1714910400,
        slug: "shenzhen-city-shanghai-port",
        finalResultOnly: false,
      },
      totalPass: 34,
      accuratePass: 26,
      totalLongBalls: 1,
      totalCross: 6,
      accurateCross: 2,
      aerialWon: 1,
      duelLost: 10,
      duelWon: 8,
      challengeLost: 1,
      dispossessed: 3,
      totalContest: 5,
      wonContest: 2,
      bigChanceCreated: 3,
      shotOffTarget: 4,
      onTargetScoringAttempt: 3,
      goals: 3,
      totalTackle: 4,
      wasFouled: 1,
      fouls: 3,
      minutesPlayed: 80,
      touches: 67,
      rating: 10,
      possessionLostCtrl: 21,
      team: {
        name: "Shanghai Port",
        slug: "shanghai-port",
        shortName: "Port",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 25453,
        nameCode: "SHP",
        disabled: false,
        national: false,
        type: 0,
        id: 41537,
        teamColors: {
          primary: "#d90000",
          secondary: "#840000",
          text: "#840000",
        },
        fieldTranslations: {
          nameTranslation: {
            ru: "\u0428\u0430\u043d\u0445\u0430\u0439 \u041f\u043e\u0440\u0442",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Mat\u00edas Vargas",
        firstName: "",
        lastName: "",
        slug: "matias-vargas",
        shortName: "M. Vargas",
        position: "M",
        jerseyNumber: "10",
        userCount: 471,
        id: 796723,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 863049600,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0641\u0627\u0631\u063a\u0627\u0633, \u0645\u0627\u062a\u064a\u0627\u0633",
          },
          shortNameTranslation: {
            ar: "\u0645. \u0641\u0627\u0631\u063a\u0627\u0633",
          },
        },
      },
      keyPass: 4,
      ratingVersions: { original: 10, alternative: 10 },
    },
    {
      event: {
        tournament: {
          name: "NB I",
          slug: "nb-i",
          category: {
            name: "Hungary",
            slug: "hungary",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 11,
            flag: "hungary",
            alpha2: "HU",
          },
          uniqueTournament: {
            name: "NB I",
            slug: "nb-i",
            primaryColorHex: "#006f51",
            secondaryColorHex: "#7abf43",
            category: {
              name: "Hungary",
              slug: "hungary",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 11,
              flag: "hungary",
              alpha2: "HU",
            },
            userCount: 13075,
            id: 187,
            displayInverseHomeAwayTeams: false,
          },
          priority: 2,
          isLive: false,
          id: 50,
        },
        customId: "wNsAN",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Ferencv\u00e1ros TC",
          slug: "ferencvaros-tc",
          shortName: "Ferencv\u00e1ros",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 74009,
          nameCode: "FTC",
          disabled: false,
          national: false,
          type: 0,
          id: 1925,
          teamColors: {
            primary: "#339900",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0641\u064a\u0631\u064a\u0646\u0643\u0641\u0627\u0631\u0648\u0633\u064a \u0628\u0648\u062f\u0627\u0628\u0633\u062a",
              ru: "\u0424\u0435\u0440\u0435\u043d\u0446\u0432\u0430\u0440\u043e\u0448",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Debreceni VSC",
          slug: "debreceni-vsc",
          shortName: "Debreceni VSC",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 6737,
          nameCode: "DEB",
          disabled: false,
          national: false,
          type: 0,
          id: 1921,
          teamColors: {
            primary: "#cc0000",
            secondary: "#cc0000",
            text: "#cc0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u062f\u064a\u0628\u0631\u0634\u064a\u0646\u064a",
              ru: "\u0424\u041a \u0414\u0435\u0431\u0440\u0435\u0446\u0435\u043d",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 5,
          display: 5,
          period1: 0,
          period2: 5,
          normaltime: 5,
        },
        awayScore: {
          current: 1,
          display: 1,
          period1: 0,
          period2: 1,
          normaltime: 1,
        },
        id: 11374988,
        startTimestamp: 1714926600,
        slug: "ferencvaros-tc-debreceni-vsc",
        finalResultOnly: false,
      },
      totalPass: 41,
      accuratePass: 36,
      totalLongBalls: 9,
      accurateLongBalls: 6,
      goalAssist: 1,
      totalCross: 9,
      accurateCross: 5,
      duelWon: 7,
      totalContest: 1,
      wonContest: 1,
      bigChanceCreated: 2,
      shotOffTarget: 2,
      onTargetScoringAttempt: 1,
      goals: 1,
      totalTackle: 3,
      wasFouled: 3,
      minutesPlayed: 80,
      touches: 67,
      rating: 9.9,
      possessionLostCtrl: 11,
      team: {
        name: "Ferencv\u00e1ros TC",
        slug: "ferencvaros-tc",
        shortName: "Ferencv\u00e1ros",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 74009,
        nameCode: "FTC",
        disabled: false,
        national: false,
        type: 0,
        id: 1925,
        teamColors: {
          primary: "#339900",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0641\u064a\u0631\u064a\u0646\u0643\u0641\u0627\u0631\u0648\u0633\u064a \u0628\u0648\u062f\u0627\u0628\u0633\u062a",
            ru: "\u0424\u0435\u0440\u0435\u043d\u0446\u0432\u0430\u0440\u043e\u0448",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Mohammad Abu Fani",
        slug: "mohammad-abu-fani",
        shortName: "M. A. Fani",
        position: "M",
        jerseyNumber: "15",
        userCount: 271,
        id: 836849,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 893635200,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0645\u062d\u0645\u062f \u0627\u0628\u0648 \u0641\u0627\u0646\u064a",
          },
          shortNameTranslation: {
            ar: "\u0645. \u0627. \u0641\u0627\u0646\u064a",
          },
        },
      },
      keyPass: 7,
      ratingVersions: { original: 9.9, alternative: 10 },
    },
    {
      event: {
        tournament: {
          name: "LaLiga",
          slug: "laliga",
          category: {
            name: "Spain",
            slug: "spain",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 32,
            flag: "spain",
            alpha2: "ES",
          },
          uniqueTournament: {
            name: "LaLiga",
            slug: "laliga",
            primaryColorHex: "#2f4a89",
            secondaryColorHex: "#f4a32e",
            category: {
              name: "Spain",
              slug: "spain",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 32,
              flag: "spain",
              alpha2: "ES",
            },
            userCount: 1118336,
            id: 8,
            displayInverseHomeAwayTeams: false,
          },
          priority: 599,
          isLive: false,
          id: 36,
        },
        customId: "tgbsihb",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 2,
        homeTeam: {
          name: "Rayo Vallecano",
          slug: "rayo-vallecano",
          shortName: "Rayo Vallecano",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 119925,
          nameCode: "RVM",
          disabled: false,
          national: false,
          type: 0,
          id: 2818,
          teamColors: {
            primary: "#ffffff",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0631\u0627\u064a\u0648 \u0641\u0627\u0644\u064a\u0643\u0627\u0646\u0648",
              ru: "\u0420\u0430\u0439\u043e \u0412\u0430\u043b\u044c\u0435\u043a\u0430\u043d\u043e",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Almer\u00eda",
          slug: "almeria",
          shortName: "Almer\u00eda",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 102082,
          nameCode: "ALM",
          disabled: false,
          national: false,
          type: 0,
          id: 2858,
          teamColors: {
            primary: "#ff0000",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0627\u0644\u0645\u064a\u0631\u064a\u0627",
              ru: "\u0410\u043b\u043c\u0435\u0440\u0438\u044f",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        awayScore: {
          current: 1,
          display: 1,
          period1: 1,
          period2: 0,
          normaltime: 1,
        },
        hasXg: true,
        id: 11368658,
        startTimestamp: 1714935600,
        slug: "almeria-rayo-vallecano",
        finalResultOnly: false,
      },
      totalPass: 37,
      accuratePass: 18,
      totalLongBalls: 27,
      accurateLongBalls: 8,
      totalClearance: 2,
      savedShotsFromInsideTheBox: 6,
      saves: 10,
      minutesPlayed: 90,
      touches: 58,
      rating: 9.8,
      possessionLostCtrl: 19,
      team: {
        name: "Almer\u00eda",
        slug: "almeria",
        shortName: "Almer\u00eda",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 102082,
        nameCode: "ALM",
        disabled: false,
        national: false,
        type: 0,
        id: 2858,
        teamColors: {
          primary: "#ff0000",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0627\u0644\u0645\u064a\u0631\u064a\u0627",
            ru: "\u0410\u043b\u043c\u0435\u0440\u0438\u044f",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Lu\u00eds Maximiano",
        firstName: "",
        lastName: "",
        slug: "luis-maximiano",
        shortName: "L. Maximiano",
        position: "G",
        jerseyNumber: "25",
        userCount: 1257,
        id: 845797,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 915494400,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0644\u0648\u064a\u0633 \u0645\u0627\u0643\u0633\u064a\u0645\u0627\u0646\u0648",
          },
          shortNameTranslation: {
            ar: "\u0644. \u0645\u0627\u0643\u0633\u064a\u0645\u0627\u0646\u0648",
          },
        },
      },
      ratingVersions: { original: 9.8, alternative: 9.6 },
      goalsPrevented: 1.4363,
    },
    {
      event: {
        tournament: {
          name: "Premier League",
          slug: "premier-league",
          category: {
            name: "England",
            slug: "england",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 1,
            flag: "england",
            alpha2: "EN",
          },
          uniqueTournament: {
            name: "Premier League",
            slug: "premier-league",
            primaryColorHex: "#3c1c5a",
            secondaryColorHex: "#f80158",
            category: {
              name: "England",
              slug: "england",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 1,
              flag: "england",
              alpha2: "EN",
            },
            userCount: 1680222,
            id: 17,
            displayInverseHomeAwayTeams: false,
          },
          priority: 600,
          isLive: false,
          id: 1,
        },
        customId: "MsN",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Chelsea",
          slug: "chelsea",
          shortName: "Chelsea",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 1399411,
          nameCode: "CHE",
          disabled: false,
          national: false,
          type: 0,
          id: 38,
          teamColors: {
            primary: "#0310a7",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u062a\u0634\u064a\u0644\u0633\u064a",
              ru: "\u0427\u0435\u043b\u0441\u0438",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "West Ham United",
          slug: "west-ham-united",
          shortName: "West Ham",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 432147,
          nameCode: "WHU",
          disabled: false,
          national: false,
          type: 0,
          id: 37,
          teamColors: {
            primary: "#66192c",
            secondary: "#59b3e4",
            text: "#59b3e4",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0648\u0633\u062a \u0647\u0627\u0645 \u064a\u0648\u0646\u0627\u064a\u062a\u062f",
              ru: "\u0412\u0435\u0441\u0442 \u0425\u044d\u043c \u042e\u043d\u0430\u0439\u0442\u0435\u0434",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 5,
          display: 5,
          period1: 3,
          period2: 2,
          normaltime: 5,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        hasXg: true,
        id: 11352494,
        startTimestamp: 1714914000,
        slug: "chelsea-west-ham-united",
        finalResultOnly: false,
      },
      totalPass: 27,
      accuratePass: 21,
      goalAssist: 1,
      aerialWon: 1,
      duelLost: 4,
      duelWon: 7,
      dispossessed: 2,
      totalContest: 5,
      wonContest: 3,
      shotOffTarget: 1,
      onTargetScoringAttempt: 4,
      blockedScoringAttempt: 2,
      goals: 2,
      totalTackle: 1,
      wasFouled: 2,
      minutesPlayed: 90,
      touches: 49,
      rating: 9.7,
      possessionLostCtrl: 13,
      expectedGoals: 1.7468,
      team: {
        name: "Chelsea",
        slug: "chelsea",
        shortName: "Chelsea",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 1399411,
        nameCode: "CHE",
        disabled: false,
        national: false,
        type: 0,
        id: 38,
        teamColors: {
          primary: "#0310a7",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u062a\u0634\u064a\u0644\u0633\u064a",
            ru: "\u0427\u0435\u043b\u0441\u0438",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Nicolas Jackson",
        firstName: "Nicolas Jackson",
        lastName: "",
        slug: "nicolas-jackson",
        shortName: "N. Jackson",
        position: "F",
        jerseyNumber: "15",
        userCount: 23108,
        id: 1085381,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 992995200,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u062c\u0627\u0643\u0633\u0648\u0646 \u060c \u0646\u064a\u0643\u0648\u0644\u0627\u0633",
          },
          shortNameTranslation: {
            ar: "\u062c. \u060c \u0646\u064a\u0643\u0648\u0644\u0627\u0633",
          },
        },
      },
      keyPass: 4,
      ratingVersions: { original: 9.7, alternative: 9.4 },
      expectedAssists: 0.0388841,
    },
    {
      event: {
        tournament: {
          name: "Liga Portugal Betclic",
          slug: "liga-portugal-betclic",
          category: {
            name: "Portugal",
            slug: "portugal",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 44,
            flag: "portugal",
            alpha2: "PT",
          },
          uniqueTournament: {
            name: "Liga Portugal Betclic",
            slug: "liga-portugal-betclic",
            primaryColorHex: "#ffc501",
            secondaryColorHex: "#e6a100",
            category: {
              name: "Portugal",
              slug: "portugal",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 44,
              flag: "portugal",
              alpha2: "PT",
            },
            userCount: 215136,
            id: 238,
            displayInverseHomeAwayTeams: false,
          },
          priority: 447,
          isLive: false,
          id: 52,
        },
        customId: "gkbsGPu",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Famalic\u00e3o",
          slug: "famalicao",
          shortName: "Famalic\u00e3o",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 27385,
          nameCode: "FAM",
          disabled: false,
          national: false,
          type: 0,
          id: 49531,
          teamColors: {
            primary: "#1a4879",
            secondary: "#222226",
            text: "#222226",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u0424\u0430\u043c\u0430\u043b\u0438\u043a\u0430\u043d",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Benfica",
          slug: "benfica",
          shortName: "Benfica",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 522770,
          nameCode: "SLB",
          disabled: false,
          national: false,
          type: 0,
          id: 3006,
          teamColors: {
            primary: "#cc0000",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0628\u0646\u0641\u064a\u0643\u0627 \u0644\u0634\u0628\u0648\u0646\u0629",
              ru: "\u0411\u0435\u043d\u0444\u0438\u043a\u0430",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 2,
          display: 2,
          period1: 0,
          period2: 2,
          normaltime: 2,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        hasXg: true,
        id: 11408335,
        startTimestamp: 1714937400,
        slug: "famalicao-benfica",
        finalResultOnly: false,
      },
      totalPass: 34,
      accuratePass: 20,
      totalLongBalls: 22,
      accurateLongBalls: 8,
      totalClearance: 1,
      savedShotsFromInsideTheBox: 6,
      saves: 10,
      totalKeeperSweeper: 1,
      accurateKeeperSweeper: 1,
      minutesPlayed: 90,
      touches: 58,
      rating: 9.7,
      possessionLostCtrl: 14,
      team: {
        name: "Famalic\u00e3o",
        slug: "famalicao",
        shortName: "Famalic\u00e3o",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 27385,
        nameCode: "FAM",
        disabled: false,
        national: false,
        type: 0,
        id: 49531,
        teamColors: {
          primary: "#1a4879",
          secondary: "#222226",
          text: "#222226",
        },
        fieldTranslations: {
          nameTranslation: {
            ru: "\u0424\u0430\u043c\u0430\u043b\u0438\u043a\u0430\u043d",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Luiz J\u00fanior",
        firstName: "Luiz L\u00facio Reis J\u00fanior",
        lastName: "",
        slug: "luiz-junior",
        shortName: "L. J\u00fanior",
        position: "G",
        jerseyNumber: "31",
        userCount: 547,
        id: 1066603,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 979430400,
      },
      ratingVersions: { original: 9.7, alternative: 9.8 },
      goalsPrevented: 2.3846,
    },
    {
      event: {
        tournament: {
          name: "The FA Women's Super League",
          slug: "the-fa-womens-super-league",
          category: {
            name: "England",
            slug: "england",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 1,
            flag: "england",
            alpha2: "EN",
          },
          uniqueTournament: {
            name: "The FA Women's Super League",
            slug: "the-fa-womens-super-league",
            primaryColorHex: "#1c0f32",
            secondaryColorHex: "#fc4342",
            category: {
              name: "England",
              slug: "england",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 1,
              flag: "england",
              alpha2: "EN",
            },
            userCount: 21868,
            id: 1044,
            displayInverseHomeAwayTeams: false,
          },
          priority: 20,
          isLive: false,
          id: 15635,
        },
        customId: "dkxstKB",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Chelsea FC Women",
          slug: "chelsea-fc-women",
          shortName: "Chelsea",
          gender: "F",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 95386,
          nameCode: "CFC",
          disabled: false,
          national: false,
          type: 0,
          id: 66768,
          teamColors: {
            primary: "#0310a7",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u0427\u0435\u043b\u0441\u0438 \u041b\u0424\u041a",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Bristol City WFC",
          slug: "bristol-city-wfc",
          shortName: "Bristol City",
          gender: "F",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 2465,
          nameCode: "BRC",
          national: false,
          type: 0,
          id: 55503,
          teamColors: {
            primary: "#ff0000",
            secondary: "#ff0000",
            text: "#ff0000",
          },
        },
        homeScore: {
          current: 8,
          display: 8,
          period1: 2,
          period2: 6,
          normaltime: 8,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        id: 11453519,
        startTimestamp: 1714931100,
        slug: "chelsea-fc-women-bristol-city-wfc",
        finalResultOnly: false,
      },
      totalPass: 27,
      accuratePass: 22,
      goalAssist: 1,
      totalCross: 1,
      aerialLost: 2,
      aerialWon: 1,
      duelLost: 5,
      duelWon: 3,
      dispossessed: 3,
      shotOffTarget: 2,
      onTargetScoringAttempt: 4,
      blockedScoringAttempt: 1,
      goals: 2,
      wasFouled: 2,
      totalOffside: 1,
      minutesPlayed: 89,
      touches: 47,
      rating: 9.6,
      possessionLostCtrl: 13,
      team: {
        name: "Chelsea FC Women",
        slug: "chelsea-fc-women",
        shortName: "Chelsea",
        gender: "F",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 95386,
        nameCode: "CFC",
        disabled: false,
        national: false,
        type: 0,
        id: 66768,
        teamColors: {
          primary: "#0310a7",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ru: "\u0427\u0435\u043b\u0441\u0438 \u041b\u0424\u041a",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Agnes Beever-Jones",
        firstName: "",
        lastName: "",
        slug: "agnes-beever-jones",
        shortName: "A. Beever-Jones",
        position: "F",
        jerseyNumber: "33",
        userCount: 382,
        id: 1100893,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 1059264000,
      },
      keyPass: 3,
      ratingVersions: { original: 9.6, alternative: 9.3 },
    },
    {
      event: {
        tournament: {
          name: "Premier League",
          slug: "premier-league",
          category: {
            name: "England",
            slug: "england",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 1,
            flag: "england",
            alpha2: "EN",
          },
          uniqueTournament: {
            name: "Premier League",
            slug: "premier-league",
            primaryColorHex: "#3c1c5a",
            secondaryColorHex: "#f80158",
            category: {
              name: "England",
              slug: "england",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 1,
              flag: "england",
              alpha2: "EN",
            },
            userCount: 1680222,
            id: 17,
            displayInverseHomeAwayTeams: false,
          },
          priority: 600,
          isLive: false,
          id: 1,
        },
        customId: "IsU",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Liverpool",
          slug: "liverpool",
          shortName: "Liverpool",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 1817159,
          nameCode: "LIV",
          disabled: false,
          national: false,
          type: 0,
          id: 44,
          teamColors: {
            primary: "#cc0000",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0644\u064a\u0641\u0631\u0628\u0648\u0644",
              ru: "\u041b\u0438\u0432\u0435\u0440\u043f\u0443\u043b\u044c",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Tottenham Hotspur",
          slug: "tottenham-hotspur",
          shortName: "Tottenham ",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 893694,
          nameCode: "TOT",
          disabled: false,
          national: false,
          type: 0,
          id: 33,
          teamColors: {
            primary: "#ffffff",
            secondary: "#000066",
            text: "#000066",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u062a\u0648\u062a\u0646\u0647\u0627\u0645 \u0647\u0648\u062a\u0633\u0628\u064a\u0631",
              ru: "\u0422\u043e\u0442\u0442\u0435\u043d\u0445\u044d\u043c \u0425\u043e\u0442\u0441\u043f\u0443\u0440",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 4,
          display: 4,
          period1: 2,
          period2: 2,
          normaltime: 4,
        },
        awayScore: {
          current: 2,
          display: 2,
          period1: 0,
          period2: 2,
          normaltime: 2,
        },
        hasXg: true,
        id: 11352500,
        startTimestamp: 1714923000,
        slug: "liverpool-tottenham-hotspur",
        finalResultOnly: false,
      },
      totalPass: 53,
      accuratePass: 47,
      totalLongBalls: 3,
      accurateLongBalls: 2,
      goalAssist: 1,
      totalCross: 2,
      accurateCross: 1,
      duelLost: 1,
      duelWon: 3,
      challengeLost: 1,
      totalContest: 1,
      wonContest: 1,
      onTargetScoringAttempt: 4,
      goals: 1,
      totalTackle: 1,
      wasFouled: 1,
      totalOffside: 1,
      minutesPlayed: 83,
      touches: 69,
      rating: 9.5,
      possessionLostCtrl: 7,
      expectedGoals: 0.3493,
      team: {
        name: "Liverpool",
        slug: "liverpool",
        shortName: "Liverpool",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 1817159,
        nameCode: "LIV",
        disabled: false,
        national: false,
        type: 0,
        id: 44,
        teamColors: {
          primary: "#cc0000",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0644\u064a\u0641\u0631\u0628\u0648\u0644",
            ru: "\u041b\u0438\u0432\u0435\u0440\u043f\u0443\u043b\u044c",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Harvey Elliott",
        firstName: "",
        lastName: "",
        slug: "harvey-elliott",
        shortName: "H. Elliott",
        position: "M",
        jerseyNumber: "19",
        userCount: 11521,
        id: 955245,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 1049414400,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0625\u0644\u064a\u0648\u062a, \u0647\u0627\u0631\u0641\u064a",
          },
          shortNameTranslation: {
            ar: "\u0647. \u0625\u0644\u064a\u0648\u062a",
          },
        },
      },
      keyPass: 5,
      ratingVersions: { original: 9.5, alternative: 9.3 },
      expectedAssists: 0.74059,
    },
    {
      event: {
        tournament: {
          name: "Premier League",
          slug: "premier-league",
          category: {
            name: "England",
            slug: "england",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 1,
            flag: "england",
            alpha2: "EN",
          },
          uniqueTournament: {
            name: "Premier League",
            slug: "premier-league",
            primaryColorHex: "#3c1c5a",
            secondaryColorHex: "#f80158",
            category: {
              name: "England",
              slug: "england",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 1,
              flag: "england",
              alpha2: "EN",
            },
            userCount: 1680222,
            id: 17,
            displayInverseHomeAwayTeams: false,
          },
          priority: 600,
          isLive: false,
          id: 1,
        },
        customId: "MsN",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Chelsea",
          slug: "chelsea",
          shortName: "Chelsea",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 1399411,
          nameCode: "CHE",
          disabled: false,
          national: false,
          type: 0,
          id: 38,
          teamColors: {
            primary: "#0310a7",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u062a\u0634\u064a\u0644\u0633\u064a",
              ru: "\u0427\u0435\u043b\u0441\u0438",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "West Ham United",
          slug: "west-ham-united",
          shortName: "West Ham",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 432147,
          nameCode: "WHU",
          disabled: false,
          national: false,
          type: 0,
          id: 37,
          teamColors: {
            primary: "#66192c",
            secondary: "#59b3e4",
            text: "#59b3e4",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0648\u0633\u062a \u0647\u0627\u0645 \u064a\u0648\u0646\u0627\u064a\u062a\u062f",
              ru: "\u0412\u0435\u0441\u0442 \u0425\u044d\u043c \u042e\u043d\u0430\u0439\u0442\u0435\u0434",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 5,
          display: 5,
          period1: 3,
          period2: 2,
          normaltime: 5,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        hasXg: true,
        id: 11352494,
        startTimestamp: 1714914000,
        slug: "chelsea-west-ham-united",
        finalResultOnly: false,
      },
      totalPass: 46,
      accuratePass: 43,
      totalLongBalls: 2,
      accurateLongBalls: 2,
      goalAssist: 1,
      totalCross: 3,
      accurateCross: 2,
      duelLost: 5,
      duelWon: 5,
      challengeLost: 1,
      totalContest: 6,
      wonContest: 3,
      bigChanceCreated: 1,
      onTargetScoringAttempt: 4,
      blockedScoringAttempt: 3,
      goals: 1,
      totalClearance: 2,
      wasFouled: 2,
      fouls: 1,
      totalOffside: 1,
      minutesPlayed: 76,
      touches: 70,
      rating: 9.5,
      possessionLostCtrl: 9,
      expectedGoals: 0.6607,
      team: {
        name: "Chelsea",
        slug: "chelsea",
        shortName: "Chelsea",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 1399411,
        nameCode: "CHE",
        disabled: false,
        national: false,
        type: 0,
        id: 38,
        teamColors: {
          primary: "#0310a7",
          secondary: "#ffffff",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u062a\u0634\u064a\u0644\u0633\u064a",
            ru: "\u0427\u0435\u043b\u0441\u0438",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Noni Madueke",
        firstName: "",
        lastName: "",
        slug: "noni-madueke",
        shortName: "N. Madueke",
        position: "F",
        jerseyNumber: "11",
        userCount: 12206,
        id: 966547,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 1015718400,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0646\u0648\u0646\u064a \u0645\u0627\u062f\u0648\u064a\u0643\u064a",
          },
          shortNameTranslation: {
            ar: "\u0646. \u0645\u0627\u062f\u0648\u064a\u0643\u064a",
          },
        },
      },
      keyPass: 6,
      ratingVersions: { original: 9.5, alternative: 9 },
      expectedAssists: 0.583191,
    },
    {
      event: {
        tournament: {
          name: "Brasileir\u00e3o S\u00e9rie A",
          slug: "brasileirao-serie-a",
          category: {
            name: "Brazil",
            slug: "brazil",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 13,
            flag: "brazil",
            alpha2: "BR",
          },
          uniqueTournament: {
            name: "Brasileir\u00e3o S\u00e9rie A",
            slug: "brasileirao-serie-a",
            primaryColorHex: "#C7FF00",
            secondaryColorHex: "#969696",
            category: {
              name: "Brazil",
              slug: "brazil",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 13,
              flag: "brazil",
              alpha2: "BR",
            },
            userCount: 339482,
            id: 325,
            displayInverseHomeAwayTeams: false,
          },
          priority: 442,
          isLive: false,
          id: 83,
        },
        customId: "hOsvP",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 3,
        homeTeam: {
          name: "Corinthians",
          slug: "corinthians",
          shortName: "Corinthians",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 279113,
          nameCode: "COR",
          disabled: false,
          national: false,
          type: 0,
          id: 1957,
          teamColors: {
            primary: "#ffffff",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u041a\u043e\u0440\u0438\u043d\u0442\u0438\u0430\u043d\u0441",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Fortaleza",
          slug: "fortaleza",
          shortName: "Fortaleza",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 107171,
          nameCode: "FOR",
          disabled: false,
          national: false,
          type: 0,
          id: 2020,
          teamColors: {
            primary: "#0000ff",
            secondary: "#ff0000",
            text: "#ff0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u0424\u043e\u0440\u0442\u0430\u043b\u0435\u0437\u0430",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        hasXg: true,
        id: 12117019,
        startTimestamp: 1714867200,
        slug: "fortaleza-corinthians",
        finalResultOnly: false,
      },
      totalPass: 22,
      accuratePass: 9,
      totalLongBalls: 19,
      accurateLongBalls: 6,
      totalClearance: 3,
      goodHighClaim: 1,
      savedShotsFromInsideTheBox: 5,
      saves: 9,
      punches: 3,
      minutesPlayed: 90,
      touches: 41,
      rating: 9.5,
      possessionLostCtrl: 14,
      team: {
        name: "Fortaleza",
        slug: "fortaleza",
        shortName: "Fortaleza",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 107171,
        nameCode: "FOR",
        disabled: false,
        national: false,
        type: 0,
        id: 2020,
        teamColors: {
          primary: "#0000ff",
          secondary: "#ff0000",
          text: "#ff0000",
        },
        fieldTranslations: {
          nameTranslation: {
            ru: "\u0424\u043e\u0440\u0442\u0430\u043b\u0435\u0437\u0430",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Jo\u00e3o Ricardo",
        slug: "joao-ricardo",
        shortName: "J. Ricardo",
        position: "G",
        jerseyNumber: "1",
        userCount: 263,
        id: 839761,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 589507200,
      },
      ratingVersions: { original: 9.5, alternative: 9.4 },
      goalsPrevented: 2.6665,
    },
    {
      event: {
        tournament: {
          name: "Allsvenskan",
          slug: "allsvenskan",
          category: {
            name: "Sweden",
            slug: "sweden",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 9,
            flag: "sweden",
            alpha2: "SE",
          },
          uniqueTournament: {
            name: "Allsvenskan",
            slug: "allsvenskan",
            primaryColorHex: "#d38509",
            secondaryColorHex: "#212759",
            category: {
              name: "Sweden",
              slug: "sweden",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 9,
              flag: "sweden",
              alpha2: "SE",
            },
            userCount: 29362,
            id: 40,
            displayInverseHomeAwayTeams: false,
          },
          priority: 139,
          isLive: false,
          id: 24,
        },
        customId: "oKsuK",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "AIK",
          slug: "aik",
          shortName: "AIK",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 19034,
          nameCode: "AIK",
          disabled: false,
          national: false,
          type: 0,
          id: 1764,
          teamColors: {
            primary: "#000000",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0623\u064a\u0643 \u0633\u0648\u0644\u0646\u0627",
              ru: "\u0410\u0418\u041a",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "IFK Norrk\u00f6ping",
          slug: "ifk-norrkoping",
          shortName: "Norrk\u00f6ping",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 10212,
          nameCode: "NKPG",
          disabled: false,
          national: false,
          type: 0,
          id: 1769,
          teamColors: {
            primary: "#ffffff",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0646\u0648\u0631\u0634\u0648\u0628\u064a\u0646\u062c",
              ru: "\u041d\u043e\u0440\u0440\u0447\u0451\u043f\u0438\u043d\u0433",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 6,
          display: 6,
          period1: 3,
          period2: 3,
          normaltime: 6,
        },
        awayScore: {
          current: 2,
          display: 2,
          period1: 0,
          period2: 2,
          normaltime: 2,
        },
        id: 11907258,
        startTimestamp: 1714919400,
        slug: "ifk-norrkoping-aik",
        finalResultOnly: false,
      },
      totalPass: 12,
      accuratePass: 11,
      totalLongBalls: 2,
      accurateLongBalls: 2,
      goalAssist: 1,
      duelLost: 3,
      duelWon: 5,
      dispossessed: 1,
      totalContest: 3,
      wonContest: 2,
      bigChanceCreated: 1,
      bigChanceMissed: 1,
      shotOffTarget: 2,
      onTargetScoringAttempt: 4,
      goals: 2,
      totalTackle: 2,
      wasFouled: 1,
      fouls: 1,
      totalOffside: 2,
      minutesPlayed: 88,
      touches: 28,
      rating: 9.5,
      possessionLostCtrl: 5,
      team: {
        name: "AIK",
        slug: "aik",
        shortName: "AIK",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 19034,
        nameCode: "AIK",
        disabled: false,
        national: false,
        type: 0,
        id: 1764,
        teamColors: {
          primary: "#000000",
          secondary: "#000000",
          text: "#000000",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0623\u064a\u0643 \u0633\u0648\u0644\u0646\u0627",
            ru: "\u0410\u0418\u041a",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Ioannis Pittas",
        firstName: "",
        lastName: "",
        slug: "ioannis-pittas",
        shortName: "I. Pittas",
        position: "F",
        jerseyNumber: "28",
        userCount: 410,
        id: 794659,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 836956800,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u064a\u0648\u0627\u0646\u064a\u0633 \u0628\u064a\u062a\u0633",
          },
          shortNameTranslation: { ar: "\u064a. \u0628\u064a\u062a\u0633" },
        },
      },
      keyPass: 1,
      ratingVersions: { original: 9.5, alternative: 9.2 },
    },
    {
      event: {
        tournament: {
          name: "Superligaen, Championship round",
          slug: "superligaen-championship-round",
          category: {
            name: "Denmark",
            slug: "denmark",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 8,
            flag: "denmark",
            alpha2: "DK",
          },
          uniqueTournament: {
            name: "Superliga",
            slug: "superliga",
            primaryColorHex: "#015a9c",
            secondaryColorHex: "#4199da",
            category: {
              name: "Denmark",
              slug: "denmark",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 8,
              flag: "denmark",
              alpha2: "DK",
            },
            userCount: 37186,
            id: 39,
            displayInverseHomeAwayTeams: false,
          },
          priority: 205,
          isLive: false,
          id: 58560,
        },
        customId: "JAsKA",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 2,
        homeTeam: {
          name: "Silkeborg IF",
          slug: "silkeborg-if",
          shortName: "Silkeborg",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 19502,
          nameCode: "SIL",
          disabled: false,
          national: false,
          type: 0,
          id: 1285,
          teamColors: {
            primary: "#ff0000",
            secondary: "#ff0000",
            text: "#ff0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0633\u064a\u0644\u0643\u064a\u0628\u0648\u0631\u062c \u0627\u064a\u0641",
              ru: "\u0421\u0438\u043b\u044c\u043a\u0435\u0431\u043e\u0440\u0433 \u0418\u0424",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "FC K\u00f8benhavn",
          slug: "fc-kobenhavn",
          shortName: "K\u00f8benhavn",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 150386,
          nameCode: "FCK",
          disabled: false,
          national: false,
          type: 0,
          id: 1284,
          teamColors: {
            primary: "#ffffff",
            secondary: "#0066ff",
            text: "#0066ff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0625\u0641 \u0633\u064a \u0643\u0648\u0628\u0646\u0647\u0627\u062c\u0646",
              ru: "\u041a\u043e\u043f\u0435\u043d\u0433\u0430\u0433\u0435\u043d",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        awayScore: {
          current: 3,
          display: 3,
          period1: 2,
          period2: 1,
          normaltime: 3,
        },
        id: 12174736,
        startTimestamp: 1714917600,
        slug: "silkeborg-if-fc-kobenhavn",
        finalResultOnly: false,
      },
      totalPass: 17,
      accuratePass: 12,
      totalLongBalls: 1,
      accurateLongBalls: 1,
      totalCross: 1,
      accurateCross: 1,
      aerialLost: 1,
      aerialWon: 1,
      duelLost: 1,
      duelWon: 3,
      totalContest: 1,
      wonContest: 1,
      bigChanceCreated: 1,
      onTargetScoringAttempt: 4,
      goals: 2,
      interceptionWon: 1,
      totalTackle: 1,
      minutesPlayed: 72,
      touches: 29,
      rating: 9.4,
      possessionLostCtrl: 6,
      team: {
        name: "FC K\u00f8benhavn",
        slug: "fc-kobenhavn",
        shortName: "K\u00f8benhavn",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 150386,
        nameCode: "FCK",
        disabled: false,
        national: false,
        type: 0,
        id: 1284,
        teamColors: {
          primary: "#ffffff",
          secondary: "#0066ff",
          text: "#0066ff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0625\u0641 \u0633\u064a \u0643\u0648\u0628\u0646\u0647\u0627\u062c\u0646",
            ru: "\u041a\u043e\u043f\u0435\u043d\u0433\u0430\u0433\u0435\u043d",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Mohamed Elyounoussi",
        slug: "mohamed-elyounoussi",
        shortName: "M. Elyounoussi",
        position: "M",
        jerseyNumber: "10",
        userCount: 1171,
        id: 119151,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 775958400,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0627\u0644\u0639\u064a\u0648\u0646\u0633\u064a, \u0645\u062d\u0645\u062f",
          },
          shortNameTranslation: {
            ar: "\u0645. \u0627\u0644\u0639\u064a\u0648\u0646\u0633\u064a",
          },
        },
      },
      keyPass: 2,
      ratingVersions: { original: 9.4, alternative: 9.3 },
    },
    {
      event: {
        tournament: {
          name: "A-League Playoffs",
          slug: "a-league-playoffs",
          category: {
            name: "Australia",
            slug: "australia",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 34,
            flag: "australia",
            alpha2: "AU",
          },
          uniqueTournament: {
            name: "A-League Men",
            slug: "a-league-men",
            primaryColorHex: "#fe5001",
            secondaryColorHex: "#8e0a06",
            category: {
              name: "Australia",
              slug: "australia",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 34,
              flag: "australia",
              alpha2: "AU",
            },
            userCount: 26947,
            id: 136,
            displayInverseHomeAwayTeams: false,
          },
          priority: 264,
          isLive: false,
          id: 7514,
        },
        customId: "vucskUq",
        status: { code: 120, description: "AP", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Melbourne Victory",
          slug: "melbourne-victory",
          shortName: "Melbourne Victory",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 18431,
          nameCode: "MEL",
          disabled: false,
          national: false,
          type: 0,
          id: 5970,
          teamColors: {
            primary: "#003366",
            secondary: "#003366",
            text: "#003366",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0645\u0644\u0628\u0648\u0631\u0646 \u0641\u064a\u0643\u062a\u0648\u0631\u064a",
              ru: "\u041c\u0435\u043b\u044c\u0431\u0443\u0440\u043d \u0412\u0438\u043a\u0442\u043e\u0440\u0438 \u0424\u041a",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Melbourne City",
          slug: "melbourne-city",
          shortName: "Melbourne City",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 30941,
          nameCode: "MBC",
          disabled: false,
          national: false,
          type: 0,
          id: 42210,
          teamColors: {
            primary: "#ffffff",
            secondary: "#66ccff",
            text: "#66ccff",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u041c\u0435\u043b\u044c\u0431\u0443\u0440\u043d \u0421\u0438\u0442\u0438",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 4,
          display: 1,
          period1: 0,
          period2: 1,
          normaltime: 1,
          extra1: 0,
          extra2: 0,
          overtime: 0,
          penalties: 3,
        },
        awayScore: {
          current: 3,
          display: 1,
          period1: 1,
          period2: 0,
          normaltime: 1,
          extra1: 0,
          extra2: 0,
          overtime: 0,
          penalties: 2,
        },
        id: 12287958,
        startTimestamp: 1714892400,
        slug: "melbourne-city-melbourne-victory",
        finalResultOnly: false,
      },
      totalPass: 46,
      accuratePass: 36,
      totalLongBalls: 1,
      goalAssist: 1,
      totalCross: 3,
      aerialLost: 6,
      aerialWon: 4,
      duelLost: 8,
      duelWon: 12,
      totalContest: 4,
      wonContest: 3,
      bigChanceCreated: 1,
      shotOffTarget: 4,
      onTargetScoringAttempt: 3,
      blockedScoringAttempt: 2,
      totalClearance: 3,
      interceptionWon: 1,
      totalTackle: 3,
      wasFouled: 2,
      fouls: 1,
      totalOffside: 1,
      minutesPlayed: 120,
      touches: 84,
      rating: 9.4,
      possessionLostCtrl: 19,
      penaltyShootoutGoal: 1,
      team: {
        name: "Melbourne City",
        slug: "melbourne-city",
        shortName: "Melbourne City",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 30941,
        nameCode: "MBC",
        disabled: false,
        national: false,
        type: 0,
        id: 42210,
        teamColors: {
          primary: "#ffffff",
          secondary: "#66ccff",
          text: "#66ccff",
        },
        fieldTranslations: {
          nameTranslation: {
            ru: "\u041c\u0435\u043b\u044c\u0431\u0443\u0440\u043d \u0421\u0438\u0442\u0438",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "L\u00e9o Natel",
        slug: "leo-natel",
        shortName: "L. Natel",
        position: "M",
        jerseyNumber: "11",
        userCount: 237,
        id: 875905,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 858297600,
      },
      keyPass: 4,
      ratingVersions: { original: 9.4, alternative: 9 },
    },
    {
      event: {
        tournament: {
          name: "Allsvenskan",
          slug: "allsvenskan",
          category: {
            name: "Sweden",
            slug: "sweden",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 9,
            flag: "sweden",
            alpha2: "SE",
          },
          uniqueTournament: {
            name: "Allsvenskan",
            slug: "allsvenskan",
            primaryColorHex: "#d38509",
            secondaryColorHex: "#212759",
            category: {
              name: "Sweden",
              slug: "sweden",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 9,
              flag: "sweden",
              alpha2: "SE",
            },
            userCount: 29362,
            id: 40,
            displayInverseHomeAwayTeams: false,
          },
          priority: 139,
          isLive: false,
          id: 24,
        },
        customId: "jKsAK",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 2,
        homeTeam: {
          name: "V\u00e4ster\u00e5s SK",
          slug: "vasteras-sk",
          shortName: "V\u00e4ster\u00e5s",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 6030,
          nameCode: "VSK",
          disabled: false,
          national: false,
          type: 0,
          id: 1775,
          teamColors: {
            primary: "#008348",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ru: "\u0412\u0435\u0441\u0442\u0435\u0440\u043e\u0441",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Djurg\u00e5rdens IF",
          slug: "djurgardens-if",
          shortName: "Djurg\u00e5rden",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 29336,
          nameCode: "DIF",
          disabled: false,
          national: false,
          type: 0,
          id: 1759,
          teamColors: {
            primary: "#33ccff",
            secondary: "#000099",
            text: "#000099",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u062f\u064a\u0648\u0631\u062c\u0627\u062f\u0646\u0632",
              ru: "\u0424\u041a \u042e\u0440\u0433\u043e\u0440\u0434\u0435\u043d",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        awayScore: {
          current: 2,
          display: 2,
          period1: 1,
          period2: 1,
          normaltime: 2,
        },
        id: 11907265,
        startTimestamp: 1714910400,
        slug: "vasteras-sk-djurgardens-if",
        finalResultOnly: false,
      },
      totalPass: 33,
      accuratePass: 11,
      totalLongBalls: 29,
      accurateLongBalls: 7,
      aerialWon: 1,
      duelWon: 1,
      totalClearance: 1,
      interceptionWon: 2,
      goodHighClaim: 3,
      savedShotsFromInsideTheBox: 6,
      penaltySave: 1,
      saves: 7,
      minutesPlayed: 90,
      touches: 50,
      rating: 9.4,
      possessionLostCtrl: 22,
      team: {
        name: "Djurg\u00e5rdens IF",
        slug: "djurgardens-if",
        shortName: "Djurg\u00e5rden",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 29336,
        nameCode: "DIF",
        disabled: false,
        national: false,
        type: 0,
        id: 1759,
        teamColors: {
          primary: "#33ccff",
          secondary: "#000099",
          text: "#000099",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u062f\u064a\u0648\u0631\u062c\u0627\u062f\u0646\u0632",
            ru: "\u0424\u041a \u042e\u0440\u0433\u043e\u0440\u0434\u0435\u043d",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Jacob Widell Zetterstr\u00f6m",
        slug: "jacob-widell-zetterstrom",
        shortName: "J. W. Zetterstr\u00f6m",
        position: "G",
        jerseyNumber: "35",
        userCount: 81,
        id: 978728,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 900115200,
      },
      ratingVersions: { original: 9.4, alternative: 9.4 },
    },
    {
      event: {
        tournament: {
          name: "Trendyol S\u00fcper Lig",
          slug: "trendyol-super-lig",
          category: {
            name: "Turkey",
            slug: "turkey",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 46,
            flag: "turkey",
            alpha2: "TR",
          },
          uniqueTournament: {
            name: "Trendyol S\u00fcper Lig",
            slug: "trendyol-super-lig",
            primaryColorHex: "#e51937",
            secondaryColorHex: "#adacac",
            category: {
              name: "Turkey",
              slug: "turkey",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 46,
              flag: "turkey",
              alpha2: "TR",
            },
            userCount: 140432,
            id: 52,
            displayInverseHomeAwayTeams: false,
          },
          priority: 440,
          isLive: false,
          id: 62,
        },
        customId: "llbsBlb",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 1,
        homeTeam: {
          name: "Galatasaray",
          slug: "galatasaray",
          shortName: "Galatasaray",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 425284,
          nameCode: "GAL",
          disabled: false,
          national: false,
          type: 0,
          id: 3061,
          teamColors: {
            primary: "#ff9900",
            secondary: "#ff0000",
            text: "#ff0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u063a\u0644\u0637\u0629 \u0633\u0631\u0627\u064a",
              ru: "\u0413\u0430\u043b\u0430\u0442\u0430\u0441\u0430\u0440\u0430\u0439",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Sivasspor",
          slug: "sivasspor",
          shortName: "Sivasspor",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 30769,
          nameCode: "SIV",
          disabled: false,
          national: false,
          type: 0,
          id: 3076,
          teamColors: {
            primary: "#cc0000",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0633\u064a\u0641\u0627\u0633 \u0633\u0628\u0648\u0631",
              ru: "\u0424\u041a \u0421\u0438\u0432\u0430\u0441\u0441\u043f\u043e\u0440",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 6,
          display: 6,
          period1: 2,
          period2: 4,
          normaltime: 6,
        },
        awayScore: {
          current: 1,
          display: 1,
          period1: 0,
          period2: 1,
          normaltime: 1,
        },
        hasXg: true,
        id: 11540867,
        startTimestamp: 1714924800,
        slug: "sivasspor-galatasaray",
        finalResultOnly: false,
      },
      totalPass: 45,
      accuratePass: 37,
      totalLongBalls: 5,
      accurateLongBalls: 3,
      goalAssist: 1,
      totalCross: 4,
      accurateCross: 1,
      duelLost: 3,
      duelWon: 1,
      challengeLost: 2,
      dispossessed: 1,
      bigChanceCreated: 1,
      shotOffTarget: 1,
      onTargetScoringAttempt: 2,
      blockedScoringAttempt: 1,
      goals: 2,
      outfielderBlock: 1,
      interceptionWon: 1,
      wasFouled: 1,
      minutesPlayed: 74,
      touches: 64,
      rating: 9.3,
      possessionLostCtrl: 15,
      expectedGoals: 0.7143,
      team: {
        name: "Galatasaray",
        slug: "galatasaray",
        shortName: "Galatasaray",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 425284,
        nameCode: "GAL",
        disabled: false,
        national: false,
        type: 0,
        id: 3061,
        teamColors: {
          primary: "#ff9900",
          secondary: "#ff0000",
          text: "#ff0000",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u063a\u0644\u0637\u0629 \u0633\u0631\u0627\u064a",
            ru: "\u0413\u0430\u043b\u0430\u0442\u0430\u0441\u0430\u0440\u0430\u0439",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Dries Mertens",
        slug: "dries-mertens",
        shortName: "D. Mertens",
        position: "M",
        jerseyNumber: "10",
        userCount: 9926,
        id: 32493,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 547257600,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u062f\u0631\u0627\u064a\u0632 \u0645\u064a\u0631\u062a\u0646\u0632",
          },
          shortNameTranslation: {
            ar: "\u062f. \u0645\u064a\u0631\u062a\u0646\u0632",
          },
        },
      },
      keyPass: 2,
      ratingVersions: { original: 9.3, alternative: 9.1 },
      expectedAssists: 0.421433,
    },
    {
      event: {
        tournament: {
          name: "First Division A, Championship Round",
          slug: "first-division-a-championship-round",
          category: {
            name: "Belgium",
            slug: "belgium",
            sport: { name: "Football", slug: "football", id: 1 },
            id: 33,
            flag: "belgium",
            alpha2: "BE",
          },
          uniqueTournament: {
            name: "Pro League",
            slug: "pro-league",
            primaryColorHex: "#16002b",
            secondaryColorHex: "#ff1740",
            category: {
              name: "Belgium",
              slug: "belgium",
              sport: { name: "Football", slug: "football", id: 1 },
              id: 33,
              flag: "belgium",
              alpha2: "BE",
            },
            userCount: 88146,
            id: 38,
            displayInverseHomeAwayTeams: false,
          },
          priority: 435,
          isLive: false,
          id: 12656,
        },
        customId: "aibskXb",
        status: { code: 100, description: "Ended", type: "finished" },
        winnerCode: 3,
        homeTeam: {
          name: "Royale Union Saint-Gilloise",
          slug: "royale-union-saint-gilloise",
          shortName: "USG",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 124297,
          nameCode: "USG",
          disabled: false,
          national: false,
          type: 0,
          id: 4860,
          teamColors: {
            primary: "#ffec06",
            secondary: "#1649fa",
            text: "#1649fa",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0627\u062a\u062d\u0627\u062f \u0633\u0627\u0646\u062a- \u062c\u064a\u0644\u0648\u064a\u0633",
              ru: "\u0421\u0435\u043d\u0442-\u0416\u0438\u043b\u043b\u0443\u0430\u0437",
            },
            shortNameTranslation: {},
          },
        },
        awayTeam: {
          name: "Anderlecht",
          slug: "anderlecht",
          shortName: "Anderlecht",
          gender: "M",
          sport: { name: "Football", slug: "football", id: 1 },
          userCount: 78143,
          nameCode: "AND",
          disabled: false,
          national: false,
          type: 0,
          id: 2900,
          teamColors: {
            primary: "#330066",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "\u0623\u0646\u062f\u0631\u0644\u062e\u062a",
              ru: "\u0410\u043d\u0434\u0435\u0440\u043b\u0435\u0445\u0442",
            },
            shortNameTranslation: {},
          },
        },
        homeScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        awayScore: {
          current: 0,
          display: 0,
          period1: 0,
          period2: 0,
          normaltime: 0,
        },
        hasXg: true,
        id: 12252589,
        startTimestamp: 1714926600,
        slug: "royale-union-saint-gilloise-anderlecht",
        finalResultOnly: false,
      },
      totalPass: 29,
      accuratePass: 21,
      totalLongBalls: 20,
      accurateLongBalls: 12,
      duelWon: 1,
      wasFouled: 1,
      savedShotsFromInsideTheBox: 5,
      saves: 9,
      minutesPlayed: 90,
      touches: 45,
      rating: 9.3,
      possessionLostCtrl: 9,
      team: {
        name: "Royale Union Saint-Gilloise",
        slug: "royale-union-saint-gilloise",
        shortName: "USG",
        gender: "M",
        sport: { name: "Football", slug: "football", id: 1 },
        userCount: 124297,
        nameCode: "USG",
        disabled: false,
        national: false,
        type: 0,
        id: 4860,
        teamColors: {
          primary: "#ffec06",
          secondary: "#1649fa",
          text: "#1649fa",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0627\u062a\u062d\u0627\u062f \u0633\u0627\u0646\u062a- \u062c\u064a\u0644\u0648\u064a\u0633",
            ru: "\u0421\u0435\u043d\u0442-\u0416\u0438\u043b\u043b\u0443\u0430\u0437",
          },
          shortNameTranslation: {},
        },
      },
      player: {
        name: "Anthony Moris",
        slug: "anthony-moris",
        shortName: "A. Moris",
        position: "G",
        jerseyNumber: "49",
        userCount: 300,
        id: 39457,
        marketValueCurrency: "EUR",
        dateOfBirthTimestamp: 641347200,
        fieldTranslations: {
          nameTranslation: {
            ar: "\u0623\u0646\u062a\u0648\u0646\u064a \u0645\u0648\u0631\u064a\u0633",
          },
          shortNameTranslation: {
            ar: "\u0623. \u0645\u0648\u0631\u064a\u0633",
          },
        },
      },
      ratingVersions: { original: 9.3, alternative: 8.9 },
      expectedAssists: 0.00678309,
      goalsPrevented: 2.1259,
    },
  ],
};
