spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.batch_size=20

logging.file.path=./logs
logging.file.max-size=50MB

rapidApiUrl=https://v3.football.api-sports.io
x-rapidapi-host=v3.football.api-sports.io
x-rapidapi-key=${X_RAPIDAPI_KEY}
rapidapi-season=2025

summer-transfer-market-end=09-08
winter-transfer-market-end=02-10

sofascoreApiBaseUrl=https://api.sofascore.com/api/v1
sofascoreEventBaseUrl=https://www.sofascore.com/api/v1

scoresApiBaseUrl=https://webws.365scores.com/web
scoresImageBaseUrl=https://imagecache.365scores.com/image/upload
scoresPlayersImageEndPoint=/v25/Athletes/
scoresClubsImageEndPoint=/v5/Competitors/

JwtSecretKey=${JWT_SECRET_KEY}

sofascore-current-season-year=25/26

server.error.include-message=always
server.port=8083